package johnshmo.woe.generation

import com.fs.starfarer.api.Global
import com.fs.starfarer.api.campaign.StarSystemAPI
import com.fs.starfarer.api.util.Misc
import johnshmo.woe.WOEGlobal


abstract class WOEStarSystem {
    @Transient
    private var cachedSystem: StarSystemAPI? = null

    val system: StarSystemAPI
        get() {
            if (cachedSystem != null) {
                return cachedSystem!!
            }
            var result: StarSystemAPI? = Global.getSector().getStarSystem(id)
            if (result != null) {
                cachedSystem = result
                return result
            }
            result = Global.getSector().createStarSystem(name)
            result.optionalUniqueId = id
            cachedSystem = result
            return result
        }

    protected val data: MutableMap<String, Any> = HashMap()
    protected abstract val id: String
    protected abstract val name: String

    protected abstract fun initializeImpl()

    fun initialize() {
        WOEGlobal.logger.info("Initializing star system: $name")

        initializeImpl()

        WOEGlobal.logger.info("Finished initializing star system: $name")
    }

    protected fun resetHyperspace() {
        for (jp in system.autogeneratedJumpPointsInHyper) {
            Misc.fadeAndExpire(jp)
        }
        system.autogeneratedJumpPointsInHyper.clear()
        if (system.hyperspaceAnchor != null) {
            Misc.fadeAndExpire(system.hyperspaceAnchor)
            system.hyperspaceAnchor = null
        }
    }
}