package johnshmo.woe.campaign.generation

import com.fs.starfarer.api.Global
import com.fs.starfarer.api.campaign.StarSystemAPI
import com.fs.starfarer.api.util.Misc
import johnshmo.woe.WOEGlobal

abstract class WOEStarSystem {
    @Transient
    private var cachedSystem: StarSystemAPI? = null

    val system: StarSystemAPI
        get() {
            if (cachedSystem != null) {
                return cachedSystem!!
            }
            var result: StarSystemAPI? = Global.getSector().getStarSystem(id)
            if (result != null) {
                cachedSystem = result
                return result
            }
            result = Global.getSector().createStarSystem(name)
            result.optionalUniqueId = id
            cachedSystem = result
            return result
        }

    private var registeredWithWideHorizons: Boolean
        get() {
            return data.contains(REGISTERED_WITH_WIDE_HORIZONS)
        }
        set(value) {
            if (value) {
                data.set(REGISTERED_WITH_WIDE_HORIZONS, true)
            } else {
                data.remove(REGISTERED_WITH_WIDE_HORIZONS)
            }
        }

    protected val data: MutableMap<String, Any> = HashMap()
    protected abstract val id: String
    protected abstract val name: String

    protected abstract fun initializeImpl()

    fun initialize() {
        WOEGlobal.logger.info("Initializing star system: $name")

        initializeImpl()

        WOEGlobal.logger.info("Finished initializing star system: $name")
    }

    protected fun resetHyperspace() {
        for (jp in system.autogeneratedJumpPointsInHyper) {
            Misc.fadeAndExpire(jp)
        }
        system.autogeneratedJumpPointsInHyper.clear()
        if (system.hyperspaceAnchor != null) {
            Misc.fadeAndExpire(system.hyperspaceAnchor)
            system.hyperspaceAnchor = null
        }
    }

    protected fun registerCoreSystem() {
        if (registeredWithWideHorizons) {
            WOEGlobal.logger.info("Already registered star system with Wide Horizons: $name")
            return
        }
        if (Global.getSettings().modManager.isModEnabled("WideHorizons")) {
            try {
                val cl = Global.getSettings().scriptClassLoader
                val api = cl.loadClass("org.widehorizons.api.WideHorizonsAPI")

                api.getMethod("registerCoreSystem", String::class.java)
                    .invoke(null, id)

                registeredWithWideHorizons = true
                WOEGlobal.logger.info("Registered core star system with Wide Horizons: $name")
            } catch (_: Throwable) {
            }
        }
    }

    protected fun registerSystem(x: Float, y: Float) {
        if (registeredWithWideHorizons) {
            WOEGlobal.logger.info("Already registered star system with Wide Horizons: $name")
            return
        }
        if (Global.getSettings().modManager.isModEnabled("WideHorizons")) {
            try {
                val cl = Global.getSettings().scriptClassLoader
                val api = cl.loadClass("org.widehorizons.api.WideHorizonsAPI")

                api.getMethod(
                    "registerSystem",
                    String::class.java,
                    Float::class.javaPrimitiveType,
                    Float::class.javaPrimitiveType
                )
                    .invoke(null, id, x, y)

                registeredWithWideHorizons = true
                WOEGlobal.logger.info("Registered star system with Wide Horizons: $name")
            } catch (_: Throwable) {
            }
        }
    }

    companion object {
        private const val REGISTERED_WITH_WIDE_HORIZONS: String = "__registeredWithWideHorizons__"

    }
}